steps:
  - command: docker build -t "docker.au.s522.net/bk/${BUILDKITE_BRANCH}/registrator:${BUILDKITE_BUILD_NUMBER}" . && docker push "docker.au.s522.net/bk/${BUILDKITE_BRANCH}/registrator:${BUILDKITE_BUILD_NUMBER}"
    label: 'Build docker image'
  - wait
  - command: docker tag "docker.au.s522.net/bk/${BUILDKITE_BRANCH}/registrator:${BUILDKITE_BUILD_NUMBER}" docker.au.s522.net/bk/master/registrator:latest && docker push docker.au.s522.net/bk/master/registrator:latest
    label: 'Push latest image'
    branches: 'master'
